teleop_twist_joy_node:
  ros__parameters:
    axis_linear:  # Left thumb stick vertical
      x: 1
    scale_linear:
      x: -2.0    # Negative so that the forward joystick movement results in forward movement
    scale_linear_turbo:
      x: -4.0

    axis_angular:  # Left thumb stick horizontal
      yaw: 0
    scale_angular:
      yaw: 4.0

    enable_button: 0  # A trigger
    enable_turbo_button: 5  # Right trigger button
